# Generated by Django 3.0.6 on 2020-05-23 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FjaleVideo', '0013_oraefundit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classroom',
        ),
        migrations.DeleteModel(
            name='Krijimematura',
        ),
        migrations.DeleteModel(
            name='Oraefundit',
        ),
    ]
