# Generated by Django 3.0.6 on 2020-05-23 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FjaleVideo', '0014_auto_20200523_0428'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Krijimelirimi',
            new_name='Classroom',
        ),
    ]
