# Generated by Django 3.0.6 on 2020-08-26 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FjaleVideo', '0015_auto_20200523_0450'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classroom',
            new_name='Krijimelirimi',
        ),
    ]
